GA: 
  - population_size: 1
  - mutation: 0
  - crossing: 0
---
Bratislava:
  - Kosice
  - Trnava
  - Moldava
  - Trencin

Kosice:
  - Bratislava
  - Trnava

Trnava:
  - Bratislava
  - Kosice
  - Trencin

Moldava:
  - Bratislava

Trencin:
  - Bratislava
  - Trnava